activation: silu
aggr: add
atom_filter: -1
attn_activation: silu
batch_size: 2048
coord_files: null
cutoff_lower: 0.0
cutoff_upper: 5.0
dataset: ANI1
dataset_arg: null
dataset_root: ~/data
derivative: false
distance_influence: both
distributed_backend: ddp
early_stopping_patience: 500
ema_alpha_dy: 1.0
ema_alpha_y: 1.0
embed_files: null
embedding_dimension: 128
energy_files: null
energy_weight: 1.0
force_files: null
force_weight: 1.0
inference_batch_size: 2048
load_model: null
log_dir: logs/
lr: 0.0007
lr_factor: 0.5
lr_min: 1.0e-07
lr_patience: 5
lr_warmup_steps: 10000
max_z: 100
model: equivariant-transformer
neighbor_embedding: true
ngpus: -1
num_epochs: 3000
num_heads: 8
num_layers: 6
num_nodes: 1
num_rbf: 32
num_workers: 6
output_model: Scalar
precision: 32
prior_model: Atomref
rbf_type: expnorm
redirect: false
reduce_op: add
save_interval: 10
splits: null
standardize: false
test_interval: 10
test_size: null
train_size: 0.8
trainable_rbf: false
val_size: 0.05
weight_decay: 0.0
