activation: silu
batch_size: 128
cutoff_lower: 0.0
cutoff_upper: 5.0
dataset: QM9
dataset_arg: energy_U0
distributed_backend: ddp
early_stopping_patience: 100
embedding_dimension: 256
inference_batch_size: 128
lr: 4.e-4
lr_factor: 0.8
lr_min: 1.e-7
lr_patience: 15
lr_warmup_steps: 0
neighbor_embedding: true
ngpus: -1
num_epochs: 3000
num_layers: 6
num_nodes: 1
num_rbf: 64
num_workers: 4
rbf_type: expnorm
save_interval: 10
seed: 1
test_interval: 10
test_size: 0.1
trainable_rbf: true
val_size: 0.05
weight_decay: 0.0