activation: silu
aggr: add
atom_filter: -1
batch_size: 8
coord_files: null
cutoff_lower: 0.0
cutoff_upper: 4.5
dataset: MD17
dataset_arg:
  molecules: revised_aspirin 
dataset_root: ~/data
derivative: true
early_stopping_patience: 300
ema_alpha_neg_dy: 1.0
ema_alpha_y: 0.01
embed_files: null
embedding_dimension: 128
energy_files: null
equivariance_invariance_group: O(3)
y_weight: 0.5
force_files: null
neg_dy_weight: 0.5
gradient_clipping: 40.0
inference_batch_size: 64
load_model: null
log_dir: logs/
lr: 0.001
lr_factor: 0.8
lr_min: 1.0e-08
lr_patience: 25
lr_warmup_steps: 500
max_num_neighbors: 32
max_z: 128
model: tensornet
ngpus: 1
num_epochs: 10000
num_layers: 2
num_nodes: 1
num_rbf: 32
num_workers: 6
output_model: Scalar
precision: 32
prior_model: null
rbf_type: expnorm
redirect: false
reduce_op: add
seed: 12345
save_interval: 10
splits: null
standardize: true
test_interval: 30
test_size: null
train_size: 950
trainable_rbf: false
val_size: 50
weight_decay: 0.0
